drop table if exists bookmarks;

create table bookmarks (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  url TEXT UNIQUE NOT NULL,
  description TEXT,
  rating INT
);

insert into bookmarks (title, url, description)
values
  ('supertest', 'https://github.com/visionmedia/supertest', 'docs for supertest'),
  ('react router', 'https://reacttraining.com/react-router/core/api/withRouter', 'docs for react router'),
  ('var vs let vs const', 'https://tylermcginnis.com/var-let-const/', 'a great article describing the differences between the basic variable declaration types'),
  ('regexr', 'https://regexr.com/', 'my favorite tool for testing out regex patterns'),
  ('node modules', 'https://flaviocopes.com/node-core-modules/', 'quick definitions for the core node modules'),
  ('xss basics', 'https://flaviocopes.com/xss/', 'a quick read on the basics of xss'),
  ('express', 'https://expressjs.com/en/4x/api.html#req', 'docs for express'),
  ('basic concepts', 'https://tylermcginnis.com/ultimate-guide-to-execution-contexts-hoisting-scopes-and-closures-in-javascript/', 'a quick guide to hoisting, closures and scope'),
  ('this: the keyword', 'https://tylermcginnis.com/this-keyword-call-apply-bind-javascript/', 'article touching base on this, call, apply and bind'),
  ('postgresql', 'https://www.postgresql.org/', 'docs for postgresql'),
  ('sql', 'https://www.sqltutorial.org/sql-cheat-sheet/', 'sql cheat sheet');